<?php include("includes/header.php");


$sesssss_id=$_SESSION['seeess_id']; 
$session_user=$_SESSION['user_login'];
//echo $_SESSION['language'];

$prods=$_REQUEST['pro_id'];

if($_SESSION['language']=='english')
{
//echo "SELECT * FROM `tbl_seller` where status='2' AND trash!='1' AND lang_status='0' order by seller_id desc"; exit;
$selectt = "SELECT * FROM `tbl_seller` where (seller_id='$prods' and status='2') AND (trash!='1' AND lang_status='0') order by seller_id desc";
}
else if($_SESSION['language']=='french')
{
$selectt = "SELECT * FROM `tbl_seller` where (seller_id='$prods' and status='2') AND (trash!='1' AND lang_status='1') order by seller_id desc";
}
else if($_SESSION['language']=='chinese')
{
$selectt = "SELECT * FROM `tbl_seller` where (seller_id='$prods' and status='2') AND (trash!='1' AND lang_status='2') order by seller_id desc";
}
else
{
$selectt = "SELECT * FROM `tbl_seller` where (seller_id='$prods' and status='2') AND (trash!='1' AND lang_status='3') order by seller_id desc";
}
//echo $selectt;

$fetch_cart_details=mysqli_fetch_array(mysqli_query($con,$selectt));

 ?>
<style type="text/css">
.classname {
	-moz-box-shadow:inset 0px 1px 0px 0px #bee2f9;
	-webkit-box-shadow:inset 0px 1px 0px 0px #bee2f9;
	box-shadow:inset 0px 1px 0px 0px #bee2f9;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #63b8ee), color-stop(1, #468ccf) );
	background:-moz-linear-gradient( center top, #63b8ee 5%, #468ccf 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#63b8ee', endColorstr='#468ccf');
	background-color:#63b8ee;
	-moz-border-radius:42px;
	-webkit-border-radius:42px;
	border-radius:42px;
	border:1px solid #3866a3;
	display:inline-block;
	color:#ededed;
	font-family:arial;
	font-size:12px;
	font-weight:bold;
	padding:1px 9px;
	text-decoration:none;
	text-shadow:1px 1px 0px #7cacde;
}.classname:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #468ccf), color-stop(1, #63b8ee) );
	background:-moz-linear-gradient( center top, #468ccf 5%, #63b8ee 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#468ccf', endColorstr='#63b8ee');
	background-color:#468ccf;
}.classname:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>

<script>
function ChangeAddress()
{
	doc = document.address;
	if(doc.fname.value=="")
	{
		doc.fname.value = doc.sfname.value;
	}
	else
	{
		doc.fname.value=""
	}
	if(doc.lname.value=="")
	{
		doc.lname.value = doc.slname.value;
	}
	else
	{
		doc.lname.value=""
	}
	if(doc.email.value=="")
	{
		doc.email.value = doc.semail.value;
	}
	else
	{
		doc.email.value=""
	}
	if(doc.ph_no.value=="")
	{
		doc.ph_no.value = doc.sph_no.value;
	}
	else
	{
		doc.ph_no.value=""
	}
	
	if(doc.address.value=="")
	{
		doc.address.value = doc.saddress.value;
	}
	else
	{
		doc.address.value=""
	}
}
</script>
<script type="text/javascript" src="lightbox.js"></script>

<div class="body-cont"> 

<div class="body-cont1"> 
<div class="body-leftcont">
<div class="cate-cont"> 
<div class="cate-heading"> <?php echo $browse; ?> </div>
<?php include("includes/sidebar.php"); ?>



</div>

<?php include("includes/innerside1.php"); ?>
</div>





<div class="body-right"> 

<?php include("includes/menu.php"); ?>

<div class="products-cate-cont" style="width:793px;"> 

<div class="products-cate-heading" style="width:773px"> <span><strong> Billing Details</strong></span></div>
<div style="border: solid 1px #CFCFCF;">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
                      <tr>
                        <td colspan="3" valign="top"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                         <tr><td colspan="2" class="bluelink" style="text-decoration:none; padding-bottom:10px;"><!--<a href="index.php"><?php echo $home; ?></a>--> <!-- <a href="products1.php" ><?php //echo $Product; ?></a>  
						 <a href="selling_buy_leads1.php?cat_id=<?php //echo $catname->c_id; ?>" > <?php //echo $catname->category; ?></a>--> </td></tr>
                            <!--<tr>
                              <td width="1%" align="left" valign="top"><img src="images/blue_head_left.jpg" width="7" height="31" /></td>
                              <td width="98%" height="25" valign="middle" class="browse_center"  ><table width="100%" border="0" cellspacing="0" cellpadding="0">-->
							    <?php

//include ("db-connect/notfound.php");
//$sess_id=$_SESSION['sess_id']; 

//$pro=$_REQUEST['pro_id'];
//echo "select * from product where id='$pro' and status='2'";
//$prouser=mysqli_query($con,"select * from product where id='$pro' and status='2'");
//$result=mysqli_fetch_array($prouser);


           ?>
                              <!--  <tr>
                                    <td width="98%" height="22" class="browsetext"><?php echo $result['p_name'];?></td>
                                  </tr>
                              </table></td>
                              <td width="1%" align="right" valign="top"><img src="images/blue_head_right.jpg" width="7" height="31" /></td>
                            </tr>-->
                        </table></td>
                      </tr>
					  <tr>
					  <td>
					  <table cellpadding="2" cellspacing="2" width="750" align="center" style="background-color:#F4F4F4;">
					  <tr>
					  <td colspan="5">
					 <a href="sellnow.php"> Back</a></td></tr>
<tr style="background-color: #CCCCCC; height:40px; border-radius:5px; font-weight:bold;">
<td width="250" align="center">Product </td>
<td width="75" align="center">Price</td>
<td width="50" align="center">Quantity</td>
<td width="50" align="center"><?php echo $delivery_type; ?></td>
<td width="75" align="center">Total Amount</td>
</tr>
<?php 

$total_pro_amount=($fetch_cart_details['price']*1);

$total=$fetch_cart_details['delivery_charge'];


$total_amt=$total+$total_pro_amount;

?>


<tr>
<td><!--<img src="productlogo/<?php echo $fetch_cart_details['p_image1']; ?>" width="100" height="100"  /> &nbsp; &nbsp;<?php echo $fetch_cart_details['product_name']; ?>-->
<table width="250" >
<tr>
<td>
<a href="companyinfo.php?id=<?php echo $fetch_cart_details['seller_id'];?>"  style="text-decoration:none;"><?php if((file_exists("uploads/". $fetch_cart_details['seller_photo']))&&($fetch_cart_details['seller_photo']!='')) { ?> <img src="<?php echo "uploads/". $fetch_cart_details['seller_photo'];?>" width="95" height="95" border="0" /><span>
<!--    <img src="<?php echo "uploads/". $fetch_cart_details['seller_photo'];?>"  width="150px" height="150px" alt="large" /><br />
-->   <?php echo $fetch_cart_details['seller_photo']; ?></span><?php } else { ?><img src="productlogo/img_noimg.jpg" width="95" height="95" border="0" /><?php } ?> </a>
</td>
<td style="color:#155A8A;"><strong><?php echo ucfirst($fetch_cart_details['seller_subject']); ?></strong></td>
</tr>
</table>
</td>
<td align="center"><?php echo $fetch_cart_details['price']; ?> <?php echo $fetch_cart_details['cur_type']; ?></td>
<td align="center">1</td>
<td align="center"><?php if($fetch_cart_details['delivery_type']=='1') { echo  $deliver_user; } elseif($fetch_cart_details['delivery_type']=='2') { echo $need_buyer; } else { }?></td>
<td align="center"><?php echo $fetch_cart_details['price']; ?> <?php echo $fetch_cart_details['cur_type']; ?></td>
</tr>
<tr>
<td colspan="5">&nbsp;</td>
</tr>



<?php ?>

<tr>
<td  colspan="5" style="border-bottom: 1px solid #D7D7D7; ">&nbsp;</td>
</tr>
<?php if($fetch_cart_details['delivery_type']=='1') { ?>
<tr>
<td align="right" colspan="2" style="color:#CC0A0A;"><strong>Total Price</strong></td><td>:</td><td><?php echo $fetch_cart_details['price']; ?> <?php echo $fetch_cart_details['cur_type']; ?></td>	
</tr>

<tr>
<td align="right" colspan="2" style="color:#CC0A0A;"><strong><?php echo $delivery_charge; ?></strong></td><td>:</td><td><?php echo $fetch_cart_details['delivery_charge']; ?> <?php echo $fetch_cart_details['del_cur_type']; ?></td>
</tr>
<?php } ?>

<tr>
<td colspan="5" style="border-top: 1px solid #D7D7D7; ">&nbsp;</td>
</tr>

<tr>
<td align="right" colspan="2" style="color:#CC0A0A;"><strong>Net Amount</strong></td><td>:</td><td><?php echo $total_amt; ?> <?php echo $fetch_cart_details['cur_type']; ?></td>
</tr>



</table>
</td>
</tr>
<tr>
<td>&nbsp;</td>
</tr>

<!--<tr>
<td align="center" style="padding-left:300px;"><a href="products1.php?DIVIDd=StabThree">Continue Shopping</a> &nbsp;&nbsp;&nbsp; <a href="billing.php">Proceed To Checkout</a></td>
</tr>
<tr>
<td>&nbsp;</td>
</tr>-->

<?php 
//echo "SELECT * FROM registration WHERE id='$session_user'"; 
$select_member=mysqli_fetch_array(mysqli_query($con,"SELECT * FROM registration WHERE id='$session_user'"));
 $coun_idddd=$select_member['country'];
//ho "SELECT * FROM country WHERE country_id='$coun_idddd'";
$con_iddd=mysqli_fetch_array(mysqli_query($con,"SELECT * FROM country WHERE country_id='$coun_idddd'"));
//echo $con_iddd['country_name'];
?>

<script type="text/javascript">
function validation_bill()
{
if(document.address.fname.value=='')
{
alert("Enter The First name");
document.address.fname.focus();
return false;
}
if(document.address.lname.value=='')
{
alert("Enter The Last name");
document.address.lname.focus();
return false;
}
if(document.address.email.value=='')
{
alert("Enter The Email");
document.address.email.focus();
return false;
}
else
{
var re=/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;  
	if(re.test(document.address.email.value)==false)
	{
	alert("Enter the Valid Email Address");
	document.address.email.focus();
	//document.register.email.value = "";
	return false;
	}

}

if(document.address.ph_no.value=='')
{
alert("Enter The Phone Number");
document.address.ph_no.focus();
return false;
}

if(document.address.address.value=='')
{
alert("Enter The Address");
document.address.address.focus();
return false;
}



}
</script>


                      <!--  <tr>
					  	<td >
						 <table cellpadding="0" cellspacing="0" border="0" width="100%" style="border-bottom:1px solid #0075b0">
						 	
						</table>
					</td>
              </tr>-->
                    </table>
<form name="address" action="billing_action.php" method="post" onsubmit="return validation_bill();" >
 <table cellpadding="2" cellspacing="2" align="center" width="750" >
 
 
 <tr>

<td colspan="2"><table cellpadding="2" cellspacing="0" width="100%" align="center" style="border:1px solid #D7D7D7; background-color:#F4F4F4; height:300px;">
<tr style=" background-color:#CCCCCC;">
<td style="font-size:16px; font-weight:bold;">Contact Details</td><td align="right"  style="color:#29B1CA;">&nbsp;</td>
</tr>
<tr>
<td>&nbsp;</td>
</tr>
<tr>
<td style=" padding-left:10px;">Firstname:</td><td><input type="text" name="fname" value=""  /></td>
</tr>
<tr>
<td style=" padding-left:10px;">Lastname:</td><td><input type="text" name="lname" value=""  /></td>
</tr>
<tr>
<td style=" padding-left:10px;">Email:</td><td><input type="text" name="email" value=""  /></td>
</tr>
<tr>
<td style=" padding-left:10px;">Phone Number:</td><td><input type="text" name="ph_no" value=""  /></td>
</tr>

<tr>
<td style=" padding-left:10px;">Address:</td><td><textarea name="address"></textarea></td>
</tr>
<tr>
<td>&nbsp;</td>
</tr>


</table></td>
</tr>
<!--<tr>
<td>&nbsp;</td>
<td><input type="checkbox" name="same_address" onclick="javascript: ChangeAddress();"   />Billing Address is the same as Shipping Address</td>
</tr>-->

  <input type="hidden" name="net_amount" value="<?php echo $total_amout; ?>" />
   
  <input type="hidden" name="prod_id" value="<?php echo $_REQUEST['pro_id']; ?>" />
 <tr>
<td width="300" style="padding-left:100px;" align="center"><a href="sellnow.php" class="classname">Back</a></td>
<?php 
$user_pay=mysqli_fetch_array(mysqli_query($con,"select * from registration where id='$session_user'"));

$paypal_email=$user_pay['paypal_id']; ?>

<td width="300"><input type="submit" name="address_submit" value="Pay" class="classname" />
  

</table>
</form>


</div>
</div>
<?php //include("includes/innerside2.php"); ?>

</div>
</div>
</div>


</div>

<?php include("includes/footer.php"); ?>