<?php 

include("includes/header.php");

//print_r($_REQUEST['property']);

 ?>

<script type="text/javascript">
  function searchlist(id) {
    var currentDiv;
    currentDiv = document.getElementById(id);
    if (currentDiv != null) {
	currentDiv.style.display = 'none';
    }
	else{  
    currentDiv.style.display = 'block';
    }
}

function checkbox() {
//alert("hai");
	var lengthcount=document.searching.maxvalue.value;
//alert(lengthcount);
	var checkedcount=0;
	for(var i=0; i<lengthcount; i++) {
	 var property = "property["+i+"]";
	 
	  var dom = document.getElementById(property);//alert(dom);
		if(dom.checked==true) {
			checkedcount++;
		}
	}
	
	if(checkedcount < 1) {
			alert("Select Atleast One product");
			return false;
		}
   else if(checkedcount>3)
   {
   	alert("Select Maximum Three Products Only ");
	return false;	
   }
}
function compare(){
 //alert("hai");
	var result=checkbox();
	if(result == false) {
		return false;
	}
	else {
	
	 document.searching.submit();
	}
}
function comp()
{
document.searching.Submit.readOnly=false;
}

function checking()
{
alert("You can't add contact to your Own Product");
}
</script>
<style type="text/css">
.classname {
	-moz-box-shadow:inset 0px 1px 0px 0px #bee2f9;
	-webkit-box-shadow:inset 0px 1px 0px 0px #bee2f9;
	box-shadow:inset 0px 1px 0px 0px #bee2f9;
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #63b8ee), color-stop(1, #468ccf) );
	background:-moz-linear-gradient( center top, #63b8ee 5%, #468ccf 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#63b8ee', endColorstr='#468ccf');
	background-color:#63b8ee;
	-moz-border-radius:42px;
	-webkit-border-radius:42px;
	border-radius:42px;
	border:1px solid #3866a3;
	display:inline-block;
	color:#ededed;
	font-family:arial;
	font-size:12px;
	font-weight:bold;
	padding:1px 9px;
	text-decoration:none;
	text-shadow:1px 1px 0px #7cacde;
}.classname:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #468ccf), color-stop(1, #63b8ee) );
	background:-moz-linear-gradient( center top, #468ccf 5%, #63b8ee 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#468ccf', endColorstr='#63b8ee');
	background-color:#468ccf;
}.classname:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>
<div class="body-cont"> 

<div class="body-cont1"> 
<div class="body-leftcont">
<div class="cate-cont"> 
<div class="cate-heading"> <?php echo $browse; ?> </div>
<?php include("includes/sidebar.php"); ?>



</div>

<?php include("includes/innerside1.php"); ?>
</div>





<div class="body-right"> 

<?php include("includes/menu.php"); ?>

<div class="products-cate-cont"> 

<div class="products-cate-heading"> <span><strong><?php echo $buy_now; ?></strong></span> <span style="float:right;"><a href="addsell_leads.php" style="font-weight:bold;"><?php echo $add_sel_lead; ?></a></span> </div>
<div style="border: solid 1px #CFCFCF;">


<?php 

$pro_name=trim($_REQUEST["p_name"]);
 $country=$_REQUEST["country"];
 $category=$_REQUEST["category"];

 /*$pro_name=trim($_REQUEST["seller_subject"]);
 $country=$_REQUEST["seller_country"];
  $category=$_REQUEST["seller_category"];*/

if($country=='0')
{
$country="";
}

if($pro_name=='Type Keyword(s)')
 {
 	$pro_name="";
 }
if($category=='0')
{
$category="";
}

if($pro_name!="")
{
session_start();
$_SESSION['pro_name']=$pro_name;
//echo $_SESSION['pro_name']; break;
 //$q1 = " AND `seller_subject` like '%$pro_name%' ";
 $q1 = " AND (`seller_subject` like '%$pro_name%' OR `seller_keyword` like '%$pro_name%' )";
}

if($country!="")
{
session_start();
$_SESSION['country']=$country;
 $q2 = " AND `seller_country` = '$country' ";
}

if($category!="")
{
session_start();
$_SESSION['category']=$category;
 $q3 = " AND `seller_category` = '$category' ";
}

$query = $q1.$q2.$q3;
 
$query =substr($query, 4);

if($query!='')
{
if($_SESSION['language']=='english')
{
$select = "SELECT * FROM `tbl_seller` WHERE $query and status='2' and payad_status='0' and lang_status='0' order by seller_id desc";
}
else if($_SESSION['language']=='french')
{
$select = "SELECT * FROM `tbl_seller` WHERE $query and status='2' and payad_status='0' and lang_status='1' order by seller_id desc";
}
else if($_SESSION['language']=='chinese')
{
$select = "SELECT * FROM `tbl_seller` WHERE $query and status='2' and payad_status='0' and lang_status='2' order by seller_id desc";
}
else
{
$select = "SELECT * FROM `tbl_seller` WHERE $query and status='2' and payad_status='0' and lang_status='3' order by seller_id desc";
}
}
else
{
if($_SESSION['language']=='english')
{
//echo "SELECT * FROM `tbl_seller` where status='2' AND trash!='1' AND lang_status='0' order by seller_id desc"; exit;
$select = "SELECT * FROM `tbl_seller` where status='2' AND trash!='1' and payad_status='0' AND lang_status='0' order by seller_id desc";
}
else if($_SESSION['language']=='french')
{
$select = "SELECT * FROM `tbl_seller` where status='2' AND trash!='1' and payad_status='0' AND lang_status='1' order by seller_id desc";
}
else if($_SESSION['language']=='chinese')
{
$select = "SELECT * FROM `tbl_seller` where status='2' AND trash!='1' and payad_status='0' AND lang_status='2' order by seller_id desc";
}
else
{
$select = "SELECT * FROM `tbl_seller` where status='2' AND trash!='1' and payad_status='0' AND lang_status='3' order by seller_id desc";
}
 }
echo $result_query;

//$select_product="SELECT * FROM product WHERE status=1";
//$res_product=mysqli_query($con,$select_product);
$strget="";
$rowsPerPage = 5;
$result_query = getPagingQuery($select, $rowsPerPage, $strget);
$result1 = mysqli_query($con,$result_query);
$pagingLink = getPagingLink($select, $rowsPerPage, "qry=$sentsql");

//echo $ss=mysqli_num_rows(mysqli_query($con,$select));
if(mysqli_num_rows($result1) > 0)
  {
?>

 
<table cellpadding="0" cellspacing="0" width="100%" style="padding-left:10px;">
<form id="form1" name="searching" method="post" action="<?php if(isset($sess_id)){?>send_action1.php<?php }else{?>login_1.php <?php } ?>">
<tr><td>&nbsp;</td></tr>

<tr>

 <td height="35"><span style="font-size:10; color:#999; font-family:Arial, Helvetica, sans-serif;"><?php echo $select_to; ?> &nbsp;&nbsp;&nbsp; <a href="#" onclick="return compare();" class="topics2"><img src="images/mail2.jpg" border="0"/> <?php echo $inquiry_now; ?>
 <!--<input name="mainSubmit" type="image" onclick="return compare();" value="Contact now" src="images/bu_ContactNow.gif"/>-->
                                </a></span></td>
                              </tr>

<?php 




$i=0;
while($fetch_product=mysqli_fetch_array($result1))
{
$res=mysqli_query($con,"select * from country where country_id=$fetch_product[seller_country]");
 $result=mysqli_fetch_array($res);
 
 $uid=$fetch_product['user_id'];

?>

<tr><td><table cellpadding="0"  cellspacing="0" width="100%">
<tr>
<td width="5%"><?php  if($uid==$sess_id){ ?>
 <input type="checkbox" name="property[<?PHP echo $i; ?>]"  id="property[<?PHP echo $i; ?>]" value="<?PHP echo $fetch_product['seller_id'] ?>"   />
 <?php } else { ?>
 <input type="checkbox" name="property[<?PHP echo $i; ?>]2"  id="property[<?PHP echo $i; ?>]" value="<?PHP echo $fetch_product['seller_id'] ?>"/>                                          <?php
   }
   ?>
</td>
<td width="10%">
<table cellpadding="0" cellspacing="0" width="100%">
<tr>
<td><a href="companyinfo.php?id=<?php echo $fetch_product['seller_id'];?>"  style="text-decoration:none;"><?php if((file_exists("uploads/". $fetch_product['seller_photo']))&&($fetch_product['seller_photo']!='')) { ?> <br /><img src="<?php echo "uploads/". $fetch_product['seller_photo'];?>" width="95" height="95" border="0" /><span>
    <!--<img src="<?php echo "uploads/". $fetch_product['seller_photo'];?>"  width="150px" height="150px" alt="large" />-->
   <?php echo ucfirst($fetch_product['seller_subject']); ?></span><?php } else { ?><img src="productlogo/img_noimg.jpg" width="95" height="95" border="0" /><?php } ?> </a></td>
</tr>
</table></td>
<td width="50%"><table cellpadding="0" cellspacing="0" width="100%">
<tr>
<td width="250">
 <input type="hidden" value="<?php echo $fetch_product['seller_id'];?>" name = "ids[]" />
 <a  class="news" href="companyinfo.php?id=<?php echo $fetch_product['seller_id'];?>"><?php echo $fetch_product['seller_subject']; ?></a></td><td width="50"><?php if((file_exists("flags/". $result['country_flag']))&&($result['country_flag']!='')) { ?><img src="flags/<?php echo $result['country_flag'];?>" width="25" height="25" border="0" /><?php } else { ?><img src="flags/no_flag.png" width="25" height="25" border="0" /><?php } ?><br /><?php echo $result['country_name']; ?></td><td width="50" class="enquire" ><a href=
							<?php 
							if(isset($sess_id))
							{
							if($uid==$sess_id)
							{ 
							?>"#" onclick="return checking();"
							<?php
							}
							else
							{
							?>
							 "send_action2.php?id=<?php echo $fetch_product['seller_id'];?>"
							 <?php
							 }
							 }else{ 
							?>"login.php" 
							<?php 
							} 
							?> class="topics2 top1"><img src="images/mail2.jpg" border="0"/> <?php echo $inquiry; ?><br /></a>
                            &nbsp;&nbsp;<?php if($fetch_product['user_id']!=$_SESSION['user_login']) { ?><a href="billing.php?pro_id=<?php echo $fetch_product['seller_id'];?>" class="classname" style="color:#FFF;"><?php echo $buy_now; ?></a> 
                            <?php } else { ?>  <a href="#" class="classname" style="color:#FFF;"><?php echo "Your Product"; ?></a>  <?php  }?>
                            </td>
</tr>
<tr>
<td><?php echo "Posted On:".str_replace(".","/",$fetch_product['seller_updated_date']); ?> </td><!--<td><?php echo $result['country_name']; ?></td>-->
</tr>
<?php
						  $uid=$fetch_product['user_id'];
  $sel=mysqli_query($con,"select * from companyprofile where user_id='$uid'");
      
	  
	   $sell=mysqli_fetch_array($sel);
	   //{
	   $compid=$sell['id'];
	   
	  $res=mysqli_query($con,"select * from companyrating where cownerid='$uid' and ratingcompany='$compid'");
	  $num=mysqli_num_rows($res);
	  $sum=0;
	  $sums=0;
	  while($fet=mysqli_fetch_array($res))
	  {
	  
	  //echo $fet['id'];
	  $rats=$fet['ratingpoint']; 
	  $sum=$sum + $rats;
	   $sums=$sum/$num;
      }
	 $sum;
	 $sums;
						  ?>


<tr>
<td><a href="company_profile.php?id=<?php echo $fetch_product['user_id'];?>" class="superdeal"><?php echo $fetch_product['seller_companyname']; ?></a>&nbsp;&nbsp;<?php echo $rating_pont; ?> (<?php echo $sums."%";?>)</td>
</tr>
</table>
</td>
</tr>

<tr><td>&nbsp;</td></tr>


</table></td></tr>

<?php $i++; } ?> 
 <input type="hidden" value="<?php echo $i; ?>" name="maxvalue" />

   </form >
</table >  

<?php } else { ?>


<div style="padding:100px; color:#FF0000; font-weight:bold;"> <?php echo $no_record; ?></div>

<?php } ?>


<div><?PHP echo $pagingLink;
     echo "<br>";?>
					  </div>
</div>
</div>
<?php include("includes/innerside2.php"); ?>

</div>
</div>
</div>


</div>

<?php include("includes/footer.php"); ?>
<?PHP
 function getPagingQuery($sql, $itemPerPage = 5)
{
	if (isset($_GET['page']) && (int)$_GET['page'] > 0) {
		$page = (int)$_GET['page'];
	} else {
		$page = 1;
	}
	
	// start fetching from this row number
	$offset = ($page - 1) * $itemPerPage;
	
	return $sql . " LIMIT $offset, $itemPerPage";
	
}
function getPagingLink($sql, $itemPerPage = 5, $strGet)
{
	global $con;
	$result        = mysqli_query($con,$sql) or die(mysqli_error($con));
	$pagingLink    = '';
	$totalResults  = mysqli_num_rows($result);
		
	
	 @$totalPages    = ceil($totalResults / $itemPerPage);
	
		
	// how many link pages to show
	$numLinks      = 10;

		
	// create the paging links only if we have more than one page of results
	if ($totalPages > 1) {
	
		$self = 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF'] ;
		
		if (isset($_GET['page']) && (int)$_GET['page'] > 0) {
			$pageNumber = (int)$_GET['page'];
		} else {
			$pageNumber = 1;
		}
		
		// print 'previous' link only if we're not
		// on page one
		if ($pageNumber > 1) {
			$page = $pageNumber - 1;
			if ($page > 1) {
				$prev = " <a href=\"$self?page=$page&$strGet\" class=\"topics2\">| Prev |</a> ";
			} else {
				$prev = " <a href=\"$self?$strGet\" class=\"topics2\">| Prev |</a> ";
			}	
				
			$first = " <a href=\"$self?$strGet\" class=\"topics2\"> First</a> ";
		} else {
			$prev  = ''; // we're on page one, don't show 'previous' link
			$first = ''; // nor 'first page' link
		}
	
		// print 'next' link only if we're not
		// on the last page
		if ($pageNumber < $totalPages) {
			$page = $pageNumber + 1;
			$next = " <a href=\"$self?page=$page&$strGet\" class=\"topics2\">| Next</a> ";
			$last = " <a href=\"$self?page=$totalPages&$strGet\" class=\"topics2\">| Last</a> ";
		} else {
			$next = ''; // we're on the last page, don't show 'next' link
			$last = ''; // nor 'last page' link
		}

		$start = $pageNumber - ($pageNumber % $numLinks) + 1;
		$end   = $start + $numLinks - 1;		
		
		$end   = min($totalPages, $end);
		
		$pagingLink = array();
		for($page = $start; $page <= $end; $page++)	{
			if ($page == $pageNumber) {
			    
				$pagingLink[] = " $page ";   // no need to create a link to current page
			} else {
				if ($page == 1) {
				  
					$pagingLink[] = " <a href=\"$self?$strGet\" class=\"topics2\">$page</a> ";
				} else {	
				 
					$pagingLink[] = " <a href=\"$self?page=$page&$strGet\" class=\"topics2\">$page</a> ";
				}	
			}
	
		}
		
		$pagingLink = implode(' | ', $pagingLink);
		
		// return the page navigation link
		$pagingLink = $first . $prev . $pagingLink . $next . $last;
		
	}
	
	
	return $pagingLink;
}
 ?> 


